version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    steps:
      - checkout
      - run:
          name: Install dependency
          command: npm install
      - run:
          name : Run test
          command: npm run test
    deploy:
      machine:
        image: ubuntu-1604:201903-01
      steps:
        - checkout
        - run:
            name: "Build docker image"
            command: docker build -t patt/twitder-ci-pat
        - run:
            name: Push to heroku registry container
            command: |
              docker login -u _ -p $(heroku auth:token) registry.heroku.com
              docker tag patt/twitder-ci-pat refistry.heroku.com/twitder-ci-pat/web
              docker push registry.heroku.com/twitder-co-pat/web
        - run:
            name: Release with heroku
            command: |
              heroku container:release web -a twitder-ci-pat
